  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  // Erc1155
  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  
  export const erc1155Abi = [
    {
      type: 'function',
      inputs: [],
      name: 'acceptOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'addressManager',
      outputs: [{ name: '', internalType: 'address', type: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'id', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'balanceOf',
      outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [
        { name: 'accounts', internalType: 'address[]', type: 'address[]' },
        { name: 'ids', internalType: 'uint256[]', type: 'uint256[]' },
      ],
      name: 'balanceOfBatch',
      outputs: [{ name: '', internalType: 'uint256[]', type: 'uint256[]' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [
        { name: '_account', internalType: 'address', type: 'address' },
        { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
        { name: '_amount', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'burn',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: '_owner', internalType: 'address', type: 'address' },
        { name: '_addressManager', internalType: 'address', type: 'address' },
        { name: '_srcToken', internalType: 'address', type: 'address' },
        { name: '_srcChainId', internalType: 'uint256', type: 'uint256' },
        { name: '_symbol', internalType: 'string', type: 'string' },
        { name: '_name', internalType: 'string', type: 'string' },
      ],
      name: 'init',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: 'account', internalType: 'address', type: 'address' },
        { name: 'operator', internalType: 'address', type: 'address' },
      ],
      name: 'isApprovedForAll',
      outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [
        { name: '_to', internalType: 'address', type: 'address' },
        { name: '_tokenId', internalType: 'uint256', type: 'uint256' },
        { name: '_amount', internalType: 'uint256', type: 'uint256' },
      ],
      name: 'mint',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: '_to', internalType: 'address', type: 'address' },
        { name: '_tokenIds', internalType: 'uint256[]', type: 'uint256[]' },
        { name: '_amounts', internalType: 'uint256[]', type: 'uint256[]' },
      ],
      name: 'mintBatch',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'name',
      outputs: [{ name: '', internalType: 'string', type: 'string' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'owner',
      outputs: [{ name: '', internalType: 'address', type: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'pause',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'paused',
      outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'pendingOwner',
      outputs: [{ name: '', internalType: 'address', type: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'proxiableUUID',
      outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'renounceOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: '_chainId', internalType: 'uint64', type: 'uint64' },
        { name: '_name', internalType: 'bytes32', type: 'bytes32' },
        { name: '_allowZeroAddress', internalType: 'bool', type: 'bool' },
      ],
      name: 'resolve',
      outputs: [{ name: '', internalType: 'address payable', type: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [
        { name: '_name', internalType: 'bytes32', type: 'bytes32' },
        { name: '_allowZeroAddress', internalType: 'bool', type: 'bool' },
      ],
      name: 'resolve',
      outputs: [{ name: '', internalType: 'address payable', type: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [
        { name: 'from', internalType: 'address', type: 'address' },
        { name: 'to', internalType: 'address', type: 'address' },
        { name: 'ids', internalType: 'uint256[]', type: 'uint256[]' },
        { name: 'amounts', internalType: 'uint256[]', type: 'uint256[]' },
        { name: 'data', internalType: 'bytes', type: 'bytes' },
      ],
      name: 'safeBatchTransferFrom',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: 'from', internalType: 'address', type: 'address' },
        { name: 'to', internalType: 'address', type: 'address' },
        { name: 'id', internalType: 'uint256', type: 'uint256' },
        { name: 'amount', internalType: 'uint256', type: 'uint256' },
        { name: 'data', internalType: 'bytes', type: 'bytes' },
      ],
      name: 'safeTransferFrom',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: 'operator', internalType: 'address', type: 'address' },
        { name: 'approved', internalType: 'bool', type: 'bool' },
      ],
      name: 'setApprovalForAll',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'srcChainId',
      outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'srcToken',
      outputs: [{ name: '', internalType: 'address', type: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [{ name: 'interfaceId', internalType: 'bytes4', type: 'bytes4' }],
      name: 'supportsInterface',
      outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [],
      name: 'symbol',
      outputs: [{ name: '', internalType: 'string', type: 'string' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
      name: 'transferOwnership',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [],
      name: 'unpause',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: 'newImplementation', internalType: 'address', type: 'address' },
      ],
      name: 'upgradeTo',
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      inputs: [
        { name: 'newImplementation', internalType: 'address', type: 'address' },
        { name: 'data', internalType: 'bytes', type: 'bytes' },
      ],
      name: 'upgradeToAndCall',
      outputs: [],
      stateMutability: 'payable',
    },
    {
      type: 'function',
      inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
      name: 'uri',
      outputs: [{ name: '', internalType: 'string', type: 'string' }],
      stateMutability: 'view',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'previousAdmin',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
        {
          name: 'newAdmin',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
      ],
      name: 'AdminChanged',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'account',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'operator',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        { name: 'approved', internalType: 'bool', type: 'bool', indexed: false },
      ],
      name: 'ApprovalForAll',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'beacon',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
      ],
      name: 'BeaconUpgraded',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        { name: 'version', internalType: 'uint8', type: 'uint8', indexed: false },
      ],
      name: 'Initialized',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'previousOwner',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'newOwner',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
      ],
      name: 'OwnershipTransferStarted',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'previousOwner',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        {
          name: 'newOwner',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
      ],
      name: 'OwnershipTransferred',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'account',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
      ],
      name: 'Paused',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'operator',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        { name: 'from', internalType: 'address', type: 'address', indexed: true },
        { name: 'to', internalType: 'address', type: 'address', indexed: true },
        {
          name: 'ids',
          internalType: 'uint256[]',
          type: 'uint256[]',
          indexed: false,
        },
        {
          name: 'values',
          internalType: 'uint256[]',
          type: 'uint256[]',
          indexed: false,
        },
      ],
      name: 'TransferBatch',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'operator',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
        { name: 'from', internalType: 'address', type: 'address', indexed: true },
        { name: 'to', internalType: 'address', type: 'address', indexed: true },
        { name: 'id', internalType: 'uint256', type: 'uint256', indexed: false },
        {
          name: 'value',
          internalType: 'uint256',
          type: 'uint256',
          indexed: false,
        },
      ],
      name: 'TransferSingle',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        { name: 'value', internalType: 'string', type: 'string', indexed: false },
        { name: 'id', internalType: 'uint256', type: 'uint256', indexed: true },
      ],
      name: 'URI',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'account',
          internalType: 'address',
          type: 'address',
          indexed: false,
        },
      ],
      name: 'Unpaused',
    },
    {
      type: 'event',
      anonymous: false,
      inputs: [
        {
          name: 'implementation',
          internalType: 'address',
          type: 'address',
          indexed: true,
        },
      ],
      name: 'Upgraded',
    },
    { type: 'error', inputs: [], name: 'BTOKEN_CANNOT_RECEIVE' },
    { type: 'error', inputs: [], name: 'BTOKEN_INVALID_PARAMS' },
    { type: 'error', inputs: [], name: 'INVALID_PAUSE_STATUS' },
    { type: 'error', inputs: [], name: 'REENTRANT_CALL' },
    { type: 'error', inputs: [], name: 'RESOLVER_DENIED' },
    { type: 'error', inputs: [], name: 'RESOLVER_INVALID_MANAGER' },
    { type: 'error', inputs: [], name: 'RESOLVER_UNEXPECTED_CHAINID' },
    {
      type: 'error',
      inputs: [
        { name: 'chainId', internalType: 'uint64', type: 'uint64' },
        { name: 'name', internalType: 'bytes32', type: 'bytes32' },
      ],
      name: 'RESOLVER_ZERO_ADDR',
    },
    { type: 'error', inputs: [], name: 'ZERO_ADDR_MANAGER' },
  ] as const
  